export interface Params {
  progress:number; duration:number; diamondCompleteTime:number; diamondHoldDuration:number; spectralEmergenceDuration:number; spectralExpansionDuration:number; ecstaticHoldDuration:number; playSpeed:number;
  morphStart:number; morphEnd:number; couplingStart:number; rotationBuildStart:number; rotationBuildEnd:number; c:number; r:number; filaments:number; initialLines:number; peakLines:number; revealSoftness:number; startSpread:number; endSpread:number; a:number; epsilon:number; omega0:number; omega1:number; speedRatio:number; counterRotation:boolean; imperfection:number; baseImperfection:number; peakImperfection:number; largeBulgeStrength:number; pinchStrength:number; spacingIrregularity:number; brightnessLandmarkStrength:number; initialHaloWidth:number; differentialRotation:number; travellingEnergyFrequency:number; travellingEnergySpeed:number; radialBreathing:number; preConvergenceEnergy:number; convergenceImpulse:number; settlingStrength:number; finalResidualMotion:number; depth:number; parallax:number; coreWidth:number; haloWidth:number; exposure:number; background:number;
  spectralExpansionSpeed:number; spectralExpansionAcceleration:number; primaryBandFrequency:number; secondaryBandAmount:number; bandSoftness:number; bandWidth:number; xExpansionScale:number; yExpansionScale:number; zExpansionScale:number; depthStretch:number; volumetricDensity:number; spectralSaturation:number; spectralVibrance:number; spectralExposure:number; spectralEmissionIntensity:number; initialSpectralBrightness:number; chromaticAmbientStrength:number; neutralAmbientStrength:number; depthChromaPreservation:number; dominantLayerColourPreservation:number; bandCentreChromaticHighlight:number; internalRidgeIntensity:number; distantChromaticFill:number; chromaticBloomStrength:number; depthAbsorption:number; overlapWhiteningThreshold:number; overlapWhiteningSoftness:number; overlapWhiteningStrength:number; violetLuminanceBoost:number; blueLuminanceBoost:number; redLuminanceBoost:number; highlightColourPreservation:number; centralWhiteStrength:number; overlapWhitening:number; waveDeformation:number; ecstaticPulseStrength:number; cameraDrift:number; residualDiamondVisibility:number; diamondSpectralFadeDuration:number; openingColourSaturation:number; openingWarmth:number; broadFieldMotion:number; radialPropagationSpeed:number; directionalSweepSpeed:number; zDepthMotion:number; densityWaveStrength:number; densityWaveSpeed:number; surfaceWarpAmount:number; rainbowHoldDuration:number; enableFinalSoftLight:boolean; softLightTransitionDuration:number; softLightHoldDuration:number; softLightBrightness:number; softLightWarmth:number; softLightUniformity:number; pearlescentResidualAmount:number; stopPlaybackAtFinal:boolean; loopCompleteSequence:boolean;
  ribbonSourceWidth:number; ribbonOuterWidth:number; ribbonWidthGrowth:number; ribbonLength:number; ribbonGrowthDuration:number; ribbonDelaySpread:number; xDirectionSpread:number; yDirectionSpread:number; zDirectionSpread:number; forwardRibbonProportion:number; backwardRibbonProportion:number; ribbonCurvature:number; secondaryBend:number; ribbonTwist:number; ribbonTwistSpeed:number; ribbonTranslucency:number; ribbonEmission:number; ribbonCentreHighlight:number; ribbonEdgeHighlight:number; ribbonOverlapBrightness:number; ribbonDepthSoftness:number; nearCameraFade:number; ribbonColourVariation:number; spectrumAcrossWidth:number; spectrumAlongLength:number; ribbonMotionSpeed:number; residualCentralGlow:number; reducedIntensity:boolean; adaptive:boolean; quality:'low'|'medium'|'high'; overlay:boolean;
}

export const defaults: Params = {
  progress:0,duration:38.7,diamondCompleteTime:18,diamondHoldDuration:4,spectralEmergenceDuration:.7,spectralExpansionDuration:2,ecstaticHoldDuration:9.3,playSpeed:1,
  morphStart:.68,morphEnd:.91,couplingStart:.62,rotationBuildStart:.05,rotationBuildEnd:.73,c:2.1,r:1.6,filaments:72,initialLines:8,peakLines:30,revealSoftness:.08,startSpread:.16,endSpread:.006,a:.79,epsilon:.13,omega0:.18,omega1:2.0,speedRatio:1.12,counterRotation:true,imperfection:.09,baseImperfection:.05,peakImperfection:.065,largeBulgeStrength:1,pinchStrength:.62,spacingIrregularity:.28,brightnessLandmarkStrength:.8,initialHaloWidth:.012,differentialRotation:.12,travellingEnergyFrequency:3,travellingEnergySpeed:1.7,radialBreathing:.045,preConvergenceEnergy:1.35,convergenceImpulse:1,settlingStrength:.92,finalResidualMotion:.08,depth:.35,parallax:.055,coreWidth:.0018,haloWidth:.025,exposure:1,background:1,
  spectralExpansionSpeed:1.9,spectralExpansionAcceleration:1.1,primaryBandFrequency:5,secondaryBandAmount:.22,bandSoftness:.58,bandWidth:.32,xExpansionScale:1.05,yExpansionScale:.82,zExpansionScale:.7,depthStretch:1.25,volumetricDensity:.95,spectralSaturation:2.65,spectralVibrance:.76,spectralExposure:1.12,spectralEmissionIntensity:5.25,initialSpectralBrightness:1.35,chromaticAmbientStrength:.28,neutralAmbientStrength:.08,depthChromaPreservation:1.2,dominantLayerColourPreservation:.82,bandCentreChromaticHighlight:.7,internalRidgeIntensity:1.15,distantChromaticFill:.3,chromaticBloomStrength:.55,depthAbsorption:.28,overlapWhiteningThreshold:6.8,overlapWhiteningSoftness:.7,overlapWhiteningStrength:.018,violetLuminanceBoost:1.82,blueLuminanceBoost:1.52,redLuminanceBoost:1.48,highlightColourPreservation:.98,centralWhiteStrength:.16,overlapWhitening:.04,waveDeformation:.28,ecstaticPulseStrength:.12,cameraDrift:.035,residualDiamondVisibility:.025,diamondSpectralFadeDuration:1,openingColourSaturation:.82,openingWarmth:.28,broadFieldMotion:1.0,radialPropagationSpeed:.9,directionalSweepSpeed:1.0,zDepthMotion:.85,densityWaveStrength:.16,densityWaveSpeed:.7,surfaceWarpAmount:.24,rainbowHoldDuration:6,enableFinalSoftLight:true,softLightTransitionDuration:3,softLightHoldDuration:5,softLightBrightness:1.65,softLightWarmth:.42,softLightUniformity:.96,pearlescentResidualAmount:.06,stopPlaybackAtFinal:true,loopCompleteSequence:false,
  ribbonSourceWidth:.012,ribbonOuterWidth:.3,ribbonWidthGrowth:1.15,ribbonLength:5.4,ribbonGrowthDuration:4.2,ribbonDelaySpread:1.1,xDirectionSpread:1,yDirectionSpread:.95,zDirectionSpread:1.05,forwardRibbonProportion:.38,backwardRibbonProportion:.42,ribbonCurvature:.62,secondaryBend:.32,ribbonTwist:.8,ribbonTwistSpeed:.48,ribbonTranslucency:.34,ribbonEmission:1.7,ribbonCentreHighlight:.5,ribbonEdgeHighlight:.9,ribbonOverlapBrightness:.8,ribbonDepthSoftness:.45,nearCameraFade:.55,ribbonColourVariation:.22,spectrumAcrossWidth:.68,spectrumAlongLength:.12,ribbonMotionSpeed:1,residualCentralGlow:.7,reducedIntensity:false,adaptive:true,quality:'medium',overlay:false
};
export const qualityFilaments = { low:48, medium:72, high:96 };
export const spectralSamples = { low:10, medium:20, high:28 };
