import type { Params } from './math/parameters';
import { qualityFilaments } from './math/parameters';
import { Timeline } from './timeline';
import { Recorder } from './recorder';

export function mountControls(root:HTMLElement,p:Params,t:Timeline,rec:Recorder,canvas:HTMLCanvasElement,onChange:()=>void){
  const panel=document.createElement('aside'); panel.className='panel';
  const fields:[keyof Params,string,number,number,number][]=[
    ['progress','Progress',0,1,.001],['duration','Duration',8,60,.5],['diamondCompleteTime','Diamond complete time',12,25,.5],['diamondHoldDuration','Diamond hold',3,5,.25],['spectralEmergenceDuration','Spectral emergence',1,4,.25],['spectralExpansionDuration','Spectral expansion',5,10,.5],['ecstaticHoldDuration','Ecstatic hold',3,8,.5],['playSpeed','Play speed',.1,3,.05],['morphStart','Morph start',.55,.85,.01],['morphEnd','Morph end',.8,.98,.01],['couplingStart','Coupling start',.5,.8,.01],['rotationBuildStart','Rotation build start',0,.2,.01],['rotationBuildEnd','Rotation build end',.55,.85,.01],
    ['c','Circle distance',1.8,2.5,.01],['r','Initial radius',1.5,1.75,.01],['startSpread','Initial spread',.02,.3,.001],['endSpread','Final spread',0,.04,.001],['a','Peak extent',.6,1,.005],['epsilon','Reciprocal epsilon',.04,.25,.005],
    ['omega0','Initial rotation',.05,.8,.01],['omega1','Peak rotation',.3,3,.01],['speedRatio','Left/right speed',.5,1.6,.01],['baseImperfection','Base imperfection',0,.15,.001],['peakImperfection','Peak imperfection',0,.4,.001],['largeBulgeStrength','Rotating bulges',0,1.8,.02],['pinchStrength','Pinch strength',0,1.4,.02],['spacingIrregularity','Spacing irregularity',0,.8,.01],['brightnessLandmarkStrength','Brightness landmarks',0,1.5,.02],['initialHaloWidth','Initial halo width',.004,.04,.001],['differentialRotation','Differential rotation',0,.4,.01],['initialLines','Initial visible lines',6,36,1],['peakLines','Peak visible lines',12,72,1],['revealSoftness','Line reveal softness',.01,.25,.01],['travellingEnergyFrequency','Energy wave frequency',1,8,.1],['travellingEnergySpeed','Energy wave speed',.2,4,.1],['radialBreathing','Radial breathing',0,.12,.005],['preConvergenceEnergy','Pre-convergence energy',.5,2.5,.05],['convergenceImpulse','Convergence impulse',0,2,.05],['settlingStrength','Settling strength',0,1.5,.05],['finalResidualMotion','Final residual motion',0,.3,.01],
    ['depth','Depth amount',0,.7,.01],['parallax','Parallax',0,.16,.002],['diamondSpectralFadeDuration','Diamond fade duration',.25,2,.05],['ribbonSourceWidth','Ribbon source width',.005,.04,.001],['ribbonOuterWidth','Ribbon outer width',.08,.3,.01],['ribbonWidthGrowth','Ribbon width growth',.5,2,.05],['ribbonLength','Ribbon length',1.5,6,.1],['ribbonGrowthDuration','Ribbon growth duration',2,8,.25],['ribbonDelaySpread','Ribbon delay spread',0,1.5,.05],['xDirectionSpread','X direction spread',.5,1.5,.05],['yDirectionSpread','Y direction spread',.5,1.5,.05],['zDirectionSpread','Z direction spread',.5,1.5,.05],['forwardRibbonProportion','Forward ribbons',0,.8,.02],['backwardRibbonProportion','Backward ribbons',0,.8,.02],['ribbonCurvature','Ribbon curvature',0,1.5,.05],['secondaryBend','Secondary bend',0,1,.05],['ribbonTwist','Ribbon twist',0,2,.05],['ribbonTwistSpeed','Twist speed',0,1.5,.05],['ribbonTranslucency','Surface translucency',.08,.8,.02],['ribbonEmission','Surface emission',.3,3,.05],['ribbonCentreHighlight','Centre highlight',.1,1,.02],['ribbonEdgeHighlight','Edge highlight',0,1.5,.05],['ribbonOverlapBrightness','Overlap brightness',0,2,.05],['ribbonDepthSoftness','Depth softness',.1,1,.02],['nearCameraFade','Near-camera fade',.25,1.5,.05],['ribbonColourVariation','Ribbon colour variation',0,.8,.02],['spectrumAcrossWidth','Spectrum across width',0,1.5,.05],['spectrumAlongLength','Spectrum along length',0,.5,.02],['ribbonMotionSpeed','Ribbon motion speed',.2,2.5,.05],['residualCentralGlow','Residual central glow',0,1.5,.05],['spectralExpansionSpeed','Expansion speed',.3,3,.05],['spectralExpansionAcceleration','Expansion acceleration',0,2,.05],['primaryBandFrequency','Primary band frequency',1,8,.1],['secondaryBandAmount','Secondary bands',0,.8,.02],['bandSoftness','Band softness',.12,1,.02],['bandWidth','Band width',.08,.8,.02],['xExpansionScale','X expansion scale',.5,1.5,.02],['yExpansionScale','Y expansion scale',.5,1.5,.02],['zExpansionScale','Z expansion scale',.3,1.5,.02],['depthStretch','Depth stretch',.3,2,.05],['volumetricDensity','Volumetric density',.2,1.5,.05],['spectralSaturation','Spectral saturation',.3,1.3,.02],['spectralExposure','Spectral exposure',.4,2.2,.02],['centralWhiteStrength','Central white strength',0,1.5,.05],['overlapWhitening','Overlap whitening',0,1.3,.05],['waveDeformation','Wave deformation',0,.8,.02],['ecstaticPulseStrength','Ecstatic pulse',0,.5,.02],['cameraDrift','Camera drift',0,.15,.005],['residualDiamondVisibility','Residual diamond',0,.5,.02],['coreWidth','Core width',.0005,.012,.0002],['haloWidth','Halo width',.005,.08,.001],['exposure','Exposure',.5,2.5,.01],['background','Background',.3,2,.01]
  ];
  const groups:[string,(keyof Params)[]][]=[
    ['Timeline',['progress','duration','diamondCompleteTime','diamondHoldDuration','spectralEmergenceDuration','spectralExpansionDuration','ecstaticHoldDuration','playSpeed','morphStart','morphEnd','couplingStart','rotationBuildStart','rotationBuildEnd']],['Initial geometry',['c','r','startSpread','endSpread']],['Peak geometry',['a','epsilon']],
    ['Motion',['omega0','omega1','speedRatio','baseImperfection','peakImperfection','largeBulgeStrength','pinchStrength','spacingIrregularity','brightnessLandmarkStrength','initialHaloWidth','differentialRotation','initialLines','peakLines','revealSoftness','travellingEnergyFrequency','travellingEnergySpeed','radialBreathing']],['Energy & settle',['preConvergenceEnergy','convergenceImpulse','settlingStrength','finalResidualMotion']],['Depth',['depth','parallax']],
    ['Full-field spectral bands',['diamondSpectralFadeDuration','spectralExpansionSpeed','spectralExpansionAcceleration','primaryBandFrequency','secondaryBandAmount','bandSoftness','bandWidth','xExpansionScale','yExpansionScale','zExpansionScale','depthStretch','volumetricDensity','spectralSaturation','spectralExposure','centralWhiteStrength','overlapWhitening','waveDeformation','ecstaticPulseStrength','cameraDrift','residualDiamondVisibility']],['Light',['coreWidth','haloWidth','exposure','background']]
  ];
  panel.innerHTML='<h1>BREAKTHROUGH FIELD</h1><label class="row"><span>Preset</span><select data-preset><option>Vivid breakthrough and spectral ecstasy</option><option>Energetic breakthrough</option><option>Ecstatic spectral bands</option></select></label><div class="buttons"><button data-action="play">Pause</button><button data-action="restart">Restart</button><button data-action="fullscreen">Fullscreen</button><button data-action="record">Record</button></div>';
  fields.push(['spectralEmissionIntensity','Spectral emission',.5,4,.05],['chromaticAmbientStrength','Chromatic ambient',0,1,.02],['depthAbsorption','Depth absorption',0,1,.02],['overlapWhiteningThreshold','Overlap whitening threshold',1,4,.05],['overlapWhiteningStrength','Overlap whitening strength',0,1,.02],['violetLuminanceBoost','Violet luminance boost',0,1,.02],['blueLuminanceBoost','Blue luminance boost',0,1,.02],['redLuminanceBoost','Red luminance boost',0,1,.02],['highlightColourPreservation','Highlight colour preservation',0,1,.02]);
  groups.push(['Spectral colour pipeline',['spectralEmissionIntensity','chromaticAmbientStrength','depthAbsorption','overlapWhiteningThreshold','overlapWhiteningStrength','violetLuminanceBoost','blueLuminanceBoost','redLuminanceBoost','highlightColourPreservation']]);
  for(const [title,keys] of groups){const section=document.createElement('section');section.className='group';section.innerHTML=`<h2>${title}</h2>`;for(const key of keys){const f=fields.find(x=>x[0]===key)!;const row=document.createElement('label');row.className='row';row.innerHTML=`<span>${f[1]}</span><span><input data-key="${key}" type="range" min="${f[2]}" max="${f[3]}" step="${f[4]}" value="${p[key]}"><output>${Number(p[key]).toFixed(3)}</output></span>`;section.append(row)}panel.append(section)}
  panel.querySelector<HTMLInputElement>('input[data-key="spectralSaturation"]')?.setAttribute('max','2');
  const performance=document.createElement('section');performance.className='group';performance.innerHTML='<h2>Performance</h2><label class="row"><span>Quality</span><select data-quality><option>low</option><option selected>medium</option><option>high</option></select></label><label class="row"><span>Adaptive</span><input data-adaptive type="checkbox" checked></label><label class="row"><span>Reduced intensity</span><input data-reduced type="checkbox"></label><label class="row"><span>Counter-rotate</span><input data-counter type="checkbox"></label>';panel.append(performance);
  const reference=document.createElement('section');reference.className='group';reference.innerHTML='<h2>Reference</h2><label class="row"><span>Overlay</span><input data-overlay type="checkbox"></label><p class="hint">Space play · R restart · F fullscreen · H controls · O overlay · 1/2/3 checkpoints</p>';panel.append(reference);root.append(panel);
  const overlay=document.createElement('div');overlay.className='overlay';root.append(overlay);
  const sync=()=>{panel.querySelectorAll<HTMLInputElement>('input[data-key]').forEach(input=>{const key=input.dataset.key as keyof Params;input.value=String(p[key]);(input.nextElementSibling as HTMLOutputElement).value=Number(p[key]).toFixed(3)});};
  panel.addEventListener('input',e=>{const target=e.target as HTMLInputElement;const key=target.dataset.key as keyof Params|undefined;if(key){(p[key] as number)=Number(target.value);if(key==='progress')t.setProgress(p.progress);if(key==='duration')t.duration=p.duration;if(key==='playSpeed')t.speed=p.playSpeed;(target.nextElementSibling as HTMLOutputElement).value=Number(target.value).toFixed(3);onChange();}});
  panel.querySelector('[data-quality]')?.addEventListener('change',e=>{p.quality=(e.target as HTMLSelectElement).value as Params['quality'];p.filaments=qualityFilaments[p.quality];p.peakLines=p.quality==='low'?24:p.quality==='medium'?36:48;onChange();});
  panel.querySelector('[data-adaptive]')?.addEventListener('change',e=>{p.adaptive=(e.target as HTMLInputElement).checked;onChange();});panel.querySelector('[data-reduced]')?.addEventListener('change',e=>{p.reducedIntensity=(e.target as HTMLInputElement).checked;onChange();});panel.querySelector('[data-counter]')?.addEventListener('change',e=>{p.counterRotation=(e.target as HTMLInputElement).checked;onChange();});
  const setOverlay=(on:boolean)=>{p.overlay=on;overlay.classList.toggle('on',on);overlay.style.backgroundImage=`url(${p.progress>.75?'/reference/peak.png':'/reference/start.png'})`;};panel.querySelector('[data-overlay]')?.addEventListener('change',e=>setOverlay((e.target as HTMLInputElement).checked));
  panel.querySelector('[data-action="play"]')?.addEventListener('click',e=>{t.playing=!t.playing;(e.target as HTMLButtonElement).textContent=t.playing?'Pause':'Play';});panel.querySelector('[data-action="restart"]')?.addEventListener('click',()=>{t.reset();p.progress=0;sync();});panel.querySelector('[data-action="fullscreen"]')?.addEventListener('click',()=>document.documentElement.requestFullscreen?.());panel.querySelector('[data-action="record"]')?.addEventListener('click',e=>{if(rec.active){rec.stop();return;}t.setProgress(0);p.progress=0;t.playing=true;rec.start(canvas,p.duration,()=>{(e.target as HTMLButtonElement).textContent='Record'});(e.target as HTMLButtonElement).textContent='Stop recording';});
  return {panel,overlay,setOverlay,sync};
}
