import type { Params } from './math/parameters';
import { qualityFilaments } from './math/parameters';
import { Timeline } from './timeline';
import { Recorder } from './recorder';

export function mountControls(root:HTMLElement,p:Params,t:Timeline,rec:Recorder,canvas:HTMLCanvasElement,onChange:()=>void){
  const panel=document.createElement('aside'); panel.className='panel';
  const fields:[keyof Params,string,number,number,number][]=[
    ['progress','Progress',0,1,.001],['duration','Duration',8,60,.5],['diamondCompleteTime','Diamond complete time',12,25,.5],['diamondHoldDuration','Diamond hold',3,5,.25],['spectralEmergenceDuration','Spectral emergence',1,4,.25],['spectralExpansionDuration','Spectral expansion',5,10,.5],['ecstaticHoldDuration','Ecstatic hold',3,8,.5],['playSpeed','Play speed',.1,3,.05],['morphStart','Morph start',.55,.85,.01],['morphEnd','Morph end',.8,.98,.01],['couplingStart','Coupling start',.5,.8,.01],['rotationBuildStart','Rotation build start',0,.2,.01],['rotationBuildEnd','Rotation build end',.55,.85,.01],
    ['c','Circle distance',1.8,2.5,.01],['r','Initial radius',1.5,1.75,.01],['startSpread','Initial spread',.02,.3,.001],['endSpread','Final spread',0,.04,.001],['a','Peak extent',.6,1,.005],['epsilon','Reciprocal epsilon',.04,.25,.005],
    ['omega0','Initial rotation',.05,.8,.01],['omega1','Peak rotation',.3,3,.01],['speedRatio','Left/right speed',.5,1.6,.01],['baseImperfection','Base imperfection',0,.15,.001],['peakImperfection','Peak imperfection',0,.4,.001],['largeBulgeStrength','Rotating bulges',0,1.8,.02],['pinchStrength','Pinch strength',0,1.4,.02],['spacingIrregularity','Spacing irregularity',0,.8,.01],['brightnessLandmarkStrength','Brightness landmarks',0,1.5,.02],['initialHaloWidth','Initial halo width',.004,.04,.001],['differentialRotation','Differential rotation',0,.4,.01],['initialLines','Initial visible lines',6,36,1],['peakLines','Peak visible lines',12,72,1],['revealSoftness','Line reveal softness',.01,.25,.01],['travellingEnergyFrequency','Energy wave frequency',1,8,.1],['travellingEnergySpeed','Energy wave speed',.2,4,.1],['radialBreathing','Radial breathing',0,.12,.005],['preConvergenceEnergy','Pre-convergence energy',.5,2.5,.05],['convergenceImpulse','Convergence impulse',0,2,.05],['settlingStrength','Settling strength',0,1.5,.05],['finalResidualMotion','Final residual motion',0,.3,.01],
    ['depth','Depth amount',0,.7,.01],['parallax','Parallax',0,.16,.002],['diamondSpectralFadeDuration','Diamond fade duration',.25,2,.05],['ribbonSourceWidth','Ribbon source width',.005,.04,.001],['ribbonOuterWidth','Ribbon outer width',.08,.3,.01],['ribbonWidthGrowth','Ribbon width growth',.5,2,.05],['ribbonLength','Ribbon length',1.5,6,.1],['ribbonGrowthDuration','Ribbon growth duration',2,8,.25],['ribbonDelaySpread','Ribbon delay spread',0,1.5,.05],['xDirectionSpread','X direction spread',.5,1.5,.05],['yDirectionSpread','Y direction spread',.5,1.5,.05],['zDirectionSpread','Z direction spread',.5,1.5,.05],['forwardRibbonProportion','Forward ribbons',0,.8,.02],['backwardRibbonProportion','Backward ribbons',0,.8,.02],['ribbonCurvature','Ribbon curvature',0,1.5,.05],['secondaryBend','Secondary bend',0,1,.05],['ribbonTwist','Ribbon twist',0,2,.05],['ribbonTwistSpeed','Twist speed',0,1.5,.05],['ribbonTranslucency','Surface translucency',.08,.8,.02],['ribbonEmission','Surface emission',.3,3,.05],['ribbonCentreHighlight','Centre highlight',.1,1,.02],['ribbonEdgeHighlight','Edge highlight',0,1.5,.05],['ribbonOverlapBrightness','Overlap brightness',0,2,.05],['ribbonDepthSoftness','Depth softness',.1,1,.02],['nearCameraFade','Near-camera fade',.25,1.5,.05],['ribbonColourVariation','Ribbon colour variation',0,.8,.02],['spectrumAcrossWidth','Spectrum across width',0,1.5,.05],['spectrumAlongLength','Spectrum along length',0,.5,.02],['ribbonMotionSpeed','Ribbon motion speed',.2,2.5,.05],['residualCentralGlow','Residual central glow',0,1.5,.05],['spectralExpansionSpeed','Expansion speed',.3,3,.05],['spectralExpansionAcceleration','Expansion acceleration',0,2,.05],['primaryBandFrequency','Primary band frequency',1,8,.1],['secondaryBandAmount','Secondary bands',0,.8,.02],['bandSoftness','Band softness',.12,1,.02],['bandWidth','Band width',.08,.8,.02],['xExpansionScale','X expansion scale',.5,1.5,.02],['yExpansionScale','Y expansion scale',.5,1.5,.02],['zExpansionScale','Z expansion scale',.3,1.5,.02],['depthStretch','Depth stretch',.3,2,.05],['volumetricDensity','Volumetric density',.2,1.5,.05],['spectralSaturation','Spectral saturation',.3,1.3,.02],['spectralExposure','Spectral exposure',.4,2.2,.02],['centralWhiteStrength','Central white strength',0,1.5,.05],['overlapWhitening','Overlap whitening',0,1.3,.05],['waveDeformation','Wave deformation',0,.8,.02],['ecstaticPulseStrength','Ecstatic pulse',0,.5,.02],['cameraDrift','Camera drift',0,.15,.005],['residualDiamondVisibility','Residual diamond',0,.5,.02],['coreWidth','Core width',.0005,.012,.0002],['haloWidth','Halo width',.005,.08,.001],['exposure','Exposure',.5,2.5,.01],['background','Background',.3,2,.01]
  ];
  const groups:[string,(keyof Params)[]][]=[
    ['Timeline',['progress','duration','diamondCompleteTime','diamondHoldDuration','spectralEmergenceDuration','spectralExpansionDuration','ecstaticHoldDuration','playSpeed','morphStart','morphEnd','couplingStart','rotationBuildStart','rotationBuildEnd']],['Initial geometry',['c','r','startSpread','endSpread']],['Peak geometry',['a','epsilon']],
    ['Motion',['omega0','omega1','speedRatio','baseImperfection','peakImperfection','largeBulgeStrength','pinchStrength','spacingIrregularity','brightnessLandmarkStrength','initialHaloWidth','differentialRotation','initialLines','peakLines','revealSoftness','travellingEnergyFrequency','travellingEnergySpeed','radialBreathing']],['Energy & settle',['preConvergenceEnergy','convergenceImpulse','settlingStrength','finalResidualMotion']],['Depth',['depth','parallax']],
    ['Full-field spectral bands',['diamondSpectralFadeDuration','spectralExpansionSpeed','spectralExpansionAcceleration','primaryBandFrequency','secondaryBandAmount','bandSoftness','bandWidth','xExpansionScale','yExpansionScale','zExpansionScale','depthStretch','volumetricDensity','spectralSaturation','spectralExposure','centralWhiteStrength','overlapWhitening','waveDeformation','ecstaticPulseStrength','cameraDrift','residualDiamondVisibility']],['Light',['coreWidth','haloWidth','exposure','background']]
  ];
  panel.innerHTML='<h1>BREAKTHROUGH FIELD</h1><label class="row"><span>Preset</span><select data-preset><option>Ecstasy resolving into light</option><option>Energetic breakthrough</option><option>Ecstatic spectral bands</option></select></label><div class="buttons"><button data-action="play">Pause</button><button data-action="restart">Restart</button><button data-action="fullscreen">Fullscreen</button><button data-action="record">Record</button></div>';
  fields.push(['openingColourSaturation','Opening colour saturation',.5,1.2,.02],['openingWarmth','Opening warmth',0,1,.02],['initialSpectralBrightness','Initial spectral brightness',.5,3,.05],['spectralVibrance','Spectral vibrance',0,1,.02],['spectralEmissionIntensity','Spectral emission',.5,6,.05],['chromaticAmbientStrength','Chromatic ambient',0,1,.02],['neutralAmbientStrength','Neutral ambient',0,1,.02],['depthChromaPreservation','Depth chroma preservation',0,2,.02],['dominantLayerColourPreservation','Dominant-layer colour preservation',0,1,.02],['bandCentreChromaticHighlight','Band-centre highlight',0,2,.02],['internalRidgeIntensity','Internal ridge intensity',0,2,.02],['distantChromaticFill','Distant chromatic fill',0,1,.02],['chromaticBloomStrength','Chromatic bloom strength',0,2,.02],['depthAbsorption','Depth absorption',0,1,.02],['overlapWhiteningThreshold','Overlap whitening threshold',1,7,.05],['overlapWhiteningSoftness','Overlap whitening softness',.1,2,.05],['overlapWhiteningStrength','Overlap whitening strength',0,1,.02],['violetLuminanceBoost','Violet luminance boost',0,2,.02],['blueLuminanceBoost','Blue luminance boost',0,2,.02],['redLuminanceBoost','Red luminance boost',0,2,.02],['highlightColourPreservation','Highlight colour preservation',0,1,.02],['broadFieldMotion','Broad field motion',0,2,.02],['radialPropagationSpeed','Radial propagation speed',0,2,.02],['directionalSweepSpeed','Directional sweep speed',0,2,.02],['zDepthMotion','Z-depth motion',0,2,.02],['densityWaveStrength','Density-wave strength',0,.5,.01],['densityWaveSpeed','Density-wave speed',0,2,.02],['surfaceWarpAmount','Surface warp amount',0,1,.02],['rainbowHoldDuration', 'Rainbow hold duration',2,12,.25]);
  groups.push(['Spectral colour pipeline',['initialSpectralBrightness','spectralVibrance','spectralEmissionIntensity','chromaticAmbientStrength','neutralAmbientStrength','depthChromaPreservation','dominantLayerColourPreservation','bandCentreChromaticHighlight','internalRidgeIntensity','distantChromaticFill','chromaticBloomStrength','depthAbsorption','overlapWhiteningThreshold','overlapWhiteningSoftness','overlapWhiteningStrength','violetLuminanceBoost','blueLuminanceBoost','redLuminanceBoost','highlightColourPreservation']]);
  groups.push(['Spectral movement',['broadFieldMotion','radialPropagationSpeed','directionalSweepSpeed','zDepthMotion','densityWaveStrength','densityWaveSpeed','surfaceWarpAmount','rainbowHoldDuration']]);
  fields.push(['softLightTransitionDuration','Rainbow-to-light transition',1,8,.25],['softLightHoldDuration','Final-light hold',2,15,.5],['softLightBrightness','Soft-light brightness',.5,3,.01],['softLightWarmth','Soft-light gold/warmth',0,1,.02],['softLightUniformity','Soft-light uniformity',0,1,.01],['pearlescentResidualAmount','Pearlescent residual',0,.3,.01],['finalBackgroundDarkness','Final background darkness',0,2,.02],['softLightOpacity','Soft-light opacity',.05,.8,.01],['finalLayerSpread','Layer spread',.4,2,.02],['finalSpatialVariation','Spatial variation',0,1,.02],['darkGapStrength','Dark-gap strength',0,1,.02],['staticWarpAmount','Static warp amount',0,.1,.005],['finalEdgeLight','Edge light amount',0,.4,.01]);
  fields.push(['finalGlowHoldDuration','Final glow hold duration',1,10,.5],['finalFadeToBlackDuration','Fade-to-black duration',.5,8,.25],['finalBlackHoldDuration','Black hold duration',1,10,.5]);
  fields.push(['depthEffectStrength','Depth effect strength',0,2,.02],['depthIntroductionPoint','Depth introduction point',0,.6,.01],['filamentBaseDepthSpread','Base-depth spread',0,.6,.01],['depthPathAmplitude','Forward/back path amplitude',0,.2,.005],['planeTilt','Plane tilt',0,.35,.01],['planeTiltVariation','Plane tilt variation',0,.3,.01],['depthPerspectiveStrength','Perspective strength',0,.6,.01],['nearWidthScale','Near width scale',.8,1.6,.02],['farWidthScale','Far width scale',.4,1,.02],['nearBrightnessScale','Near brightness scale',.8,1.6,.02],['farBrightnessScale','Far brightness scale',.4,1,.02],['depthParallax','Depth parallax',0,.3,.01],['depthAtmosphericAttenuation','Depth atmospheric attenuation',0,.5,.01],['convergenceDepthCollapse','Convergence depth collapse',0,1,.02]);
  fields.push(['enableTrue3DStrands','Enable true 3D strands',0,1,1],['depthIntroductionTime','Depth introduction time',0,8,.1],['maxPlaneTilt','Maximum plane tilt',0,.6,.01],['planeTiltVariation3D','Plane tilt variation',0,.6,.01],['baseDepthSpread3D','Base-depth spread',0,.5,.01],['orbitZAmplitude','Orbit z amplitude',0,.7,.01],['secondaryZAmplitude','Secondary z amplitude',0,.25,.01],['perspectiveStrength3D','Perspective strength',0,1,.02],['nearWidthScale3D','Near width scale',.5,2,.02],['farWidthScale3D','Far width scale',.3,1,.02],['nearBrightnessScale3D','Near brightness scale',.5,2,.02],['farBrightnessScale3D','Far brightness scale',.3,1,.02],['depthAttenuation3D','Depth attenuation',0,1,.02],['coreOpacity3D','Core opacity',.2,1,.02],['depthTestedGlowStrength','Depth-tested glow strength',0,1,.02],['enableDepartures','Enable departures',0,1,1],['departureEarliestTime','Earliest departure time',0,12,.1],['departureLatestTime','Latest departure time',1,16,.1],['departureDuration','Departure duration',.5,3,.1],['departingStrandProportion','Departing strand proportion',0,.6,.01],['strongDepartureProportion','Strong departure proportion',0,.25,.01],['tangentContinuationStrength','Tangent continuation',0,1.5,.02],['departureLength','Departure length',0,2,.02],['horizontalBend','Horizontal bend',0,1.5,.02],['verticalBend','Vertical bend',0,1.5,.02],['zBend','Z bend',0,1,.02],['endTaper','End taper',0,1,.02],['sideContainment3D','Side containment',0,1,.02],['departureCollapseTiming','Departure collapse timing',0,.8,.02]);
  fields.push(['initialStripWidth3D','Initial core width',.001,.01,.0002],['energeticStripWidth3D','Energetic core width',.002,.012,.0002],['initialGlowScale3D','Initial halo width',1,3,.02],['energeticGlowScale3D','Energetic halo width',1.2,3,.02],['initialCoreEmission3D','Initial core emission',.2,1.2,.01],['peakCoreEmission3D','Peak core emission',.8,2.5,.01],['initialHaloEmission3D','Initial halo emission',.1,1,.01],['peakHaloEmission3D','Peak halo emission',.2,1.5,.01],['brightnessRiseStartTime3D','Brightness rise start time',0,3,.1],['brightnessRiseDuration3D','Brightness rise duration',2,14,.1],['brightnessExponent3D','Brightness exponent',1,2,.05],['openingBronzeColour3D','Opening bronze colour',0,1,.01],['energeticBronzeGold3D','Energetic bronze-gold colour',0,1,.01],['goldTransitionStartTime3D','Initial bronze hold (progress)',.05,.5,.01],['goldTransitionDuration3D','Soft-gold transition completion (progress)',.3,.9,.01],['middleSoftGold3D','Middle soft-gold colour',0,1,.01],['energeticChampagne3D','Energetic champagne colour',0,1,.01],['peakSoftGold3D','Peak soft-gold colour',0,1,.01],['goldSoftness3D','Soft-gold transition curve',.7,1.2,.01],['nearDiamondColourInfluence3D','Near-diamond colour influence',0,1,.01],['nearDepthGoldShift3D','Near-depth gold shift',0,1,.01],['haloGoldSoftness3D','Halo-softness transition',0,1,.01]);
  groups.push(['Opening bronze',['openingColourSaturation','openingWarmth']],['Opening filament appearance',['initialStripWidth3D','energeticStripWidth3D','initialGlowScale3D','energeticGlowScale3D','initialCoreEmission3D','peakCoreEmission3D','initialHaloEmission3D','peakHaloEmission3D','brightnessRiseStartTime3D','brightnessRiseDuration3D','brightnessExponent3D','openingBronzeColour3D','energeticBronzeGold3D','goldTransitionStartTime3D','goldTransitionDuration3D','middleSoftGold3D','energeticChampagne3D','peakSoftGold3D','goldSoftness3D','nearDiamondColourInfluence3D','nearDepthGoldShift3D','haloGoldSoftness3D']],['Final soft light',['softLightTransitionDuration','softLightHoldDuration','softLightBrightness','softLightWarmth','softLightUniformity','pearlescentResidualAmount','finalBackgroundDarkness','softLightOpacity','finalLayerSpread','finalSpatialVariation','darkGapStrength','staticWarpAmount','finalEdgeLight']]);
  groups.push(['Fade to black',['finalGlowHoldDuration','finalFadeToBlackDuration','finalBlackHoldDuration']]);
  groups.push(['Rotational depth',['depthEffectStrength','depthIntroductionPoint','filamentBaseDepthSpread','depthPathAmplitude','planeTilt','planeTiltVariation','depthPerspectiveStrength','nearWidthScale','farWidthScale','nearBrightnessScale','farBrightnessScale','depthParallax','depthAtmosphericAttenuation','convergenceDepthCollapse']]);
  groups.push(['True 3D filament field',['enableTrue3DStrands','depthIntroductionTime','maxPlaneTilt','planeTiltVariation3D','baseDepthSpread3D','orbitZAmplitude','secondaryZAmplitude','perspectiveStrength3D','nearWidthScale3D','farWidthScale3D','nearBrightnessScale3D','farBrightnessScale3D','depthAttenuation3D','coreOpacity3D','depthTestedGlowStrength']]);
  groups.push(['Delayed strand departure',['enableDepartures','departureEarliestTime','departureLatestTime','departureDuration','departingStrandProportion','strongDepartureProportion','tangentContinuationStrength','departureLength','horizontalBend','verticalBend','zBend','endTaper','sideContainment3D','departureCollapseTiming']]);
  for(const [title,keys] of groups){const section=document.createElement('section');section.className='group';section.innerHTML=`<h2>${title}</h2>`;for(const key of keys){const f=fields.find(x=>x[0]===key)!;const row=document.createElement('label');row.className='row';row.innerHTML=`<span>${f[1]}</span><span><input data-key="${key}" type="range" min="${f[2]}" max="${f[3]}" step="${f[4]}" value="${p[key]}"><output>${Number(p[key]).toFixed(3)}</output></span>`;section.append(row)}panel.append(section)}
  panel.querySelector<HTMLInputElement>('input[data-key="spectralSaturation"]')?.setAttribute('max','3.5');
  panel.querySelector<HTMLInputElement>('input[data-key="spectralEmergenceDuration"]')?.setAttribute('min','.25');
  panel.querySelector<HTMLInputElement>('input[data-key="spectralExpansionDuration"]')?.setAttribute('min','.75');
  panel.querySelector<HTMLInputElement>('input[data-key="spectralExpansionDuration"]')?.setAttribute('max','4');
  panel.querySelector<HTMLInputElement>('input[data-key="ecstaticHoldDuration"]')?.setAttribute('max','12');
  const performance=document.createElement('section');performance.className='group';performance.innerHTML='<h2>Performance</h2><label class="row"><span>Quality</span><select data-quality><option>low</option><option selected>medium</option><option>high</option></select></label><label class="row"><span>Adaptive</span><input data-adaptive type="checkbox" checked></label><label class="row"><span>Reduced intensity</span><input data-reduced type="checkbox"></label><label class="row"><span>Counter-rotate</span><input data-counter type="checkbox"></label>';panel.append(performance);
  const finalOptions=document.createElement('section');finalOptions.className='group';finalOptions.innerHTML='<h2>Final soft light</h2><label class="row"><span>Enable final soft light</span><input data-soft-light type="checkbox" checked></label><label class="row"><span>Stop at final frame</span><input data-stop-final type="checkbox" checked></label><label class="row"><span>Loop complete sequence</span><input data-loop-final type="checkbox"></label>';panel.append(finalOptions);
  const fadeOptions=document.createElement('section');fadeOptions.className='group';fadeOptions.innerHTML='<h2>Fade to black</h2><label class="row"><span>Enable final fade to black</span><input data-fade-black type="checkbox" checked></label><label class="row"><span>Stop playback on black</span><input data-stop-black type="checkbox" checked></label><label class="row"><span>Loop after black</span><input data-loop-black type="checkbox"></label>';panel.append(fadeOptions);
  const reference=document.createElement('section');reference.className='group';reference.innerHTML='<h2>Reference</h2><label class="row"><span>Overlay</span><input data-overlay type="checkbox"></label><p class="hint">Space play · R restart · F fullscreen · H controls · O overlay · 1/2/3 checkpoints</p>';panel.append(reference);root.append(panel);
  const overlay=document.createElement('div');overlay.className='overlay';root.append(overlay);
  const sync=()=>{panel.querySelectorAll<HTMLInputElement>('input[data-key]').forEach(input=>{const key=input.dataset.key as keyof Params;input.value=String(p[key]);(input.nextElementSibling as HTMLOutputElement).value=Number(p[key]).toFixed(3)});};
  panel.addEventListener('input',e=>{const target=e.target as HTMLInputElement;const key=target.dataset.key as keyof Params|undefined;if(key){(p[key] as number)=Number(target.value);if(key==='progress')t.setProgress(p.progress);if(key==='duration')t.duration=p.duration;if(key==='playSpeed')t.speed=p.playSpeed;(target.nextElementSibling as HTMLOutputElement).value=Number(target.value).toFixed(3);onChange();}});
  panel.querySelector('[data-quality]')?.addEventListener('change',e=>{p.quality=(e.target as HTMLSelectElement).value as Params['quality'];p.filaments=qualityFilaments[p.quality];p.peakLines=p.quality==='low'?24:p.quality==='medium'?36:48;onChange();});
  panel.querySelector('[data-adaptive]')?.addEventListener('change',e=>{p.adaptive=(e.target as HTMLInputElement).checked;onChange();});panel.querySelector('[data-reduced]')?.addEventListener('change',e=>{p.reducedIntensity=(e.target as HTMLInputElement).checked;onChange();});panel.querySelector('[data-counter]')?.addEventListener('change',e=>{p.counterRotation=(e.target as HTMLInputElement).checked;onChange();});
  panel.querySelector('[data-soft-light]')?.addEventListener('change',e=>{p.enableFinalSoftLight=(e.target as HTMLInputElement).checked;onChange();});panel.querySelector('[data-stop-final]')?.addEventListener('change',e=>{p.stopPlaybackAtFinal=(e.target as HTMLInputElement).checked;onChange();});panel.querySelector('[data-loop-final]')?.addEventListener('change',e=>{p.loopCompleteSequence=(e.target as HTMLInputElement).checked;onChange();});
  panel.querySelector('[data-fade-black]')?.addEventListener('change',e=>{p.enableFinalFadeToBlack=(e.target as HTMLInputElement).checked;onChange();});panel.querySelector('[data-stop-black]')?.addEventListener('change',e=>{p.stopPlaybackOnBlack=(e.target as HTMLInputElement).checked;onChange();});panel.querySelector('[data-loop-black]')?.addEventListener('change',e=>{p.loopAfterBlack=(e.target as HTMLInputElement).checked;onChange();});
  const setOverlay=(on:boolean)=>{p.overlay=on;overlay.classList.toggle('on',on);overlay.style.backgroundImage=`url(${p.progress>.75?'/reference/peak.png':'/reference/start.png'})`;};panel.querySelector('[data-overlay]')?.addEventListener('change',e=>setOverlay((e.target as HTMLInputElement).checked));
  panel.querySelector('[data-action="play"]')?.addEventListener('click',e=>{t.playing=!t.playing;(e.target as HTMLButtonElement).textContent=t.playing?'Pause':'Play';});panel.querySelector('[data-action="restart"]')?.addEventListener('click',()=>{t.reset();p.progress=0;sync();});panel.querySelector('[data-action="fullscreen"]')?.addEventListener('click',()=>document.documentElement.requestFullscreen?.());panel.querySelector('[data-action="record"]')?.addEventListener('click',e=>{if(rec.active){rec.stop();return;}t.setProgress(0);p.progress=0;t.playing=true;rec.start(canvas,p.duration,()=>{(e.target as HTMLButtonElement).textContent='Record'});(e.target as HTMLButtonElement).textContent='Stop recording';});
  return {panel,overlay,setOverlay,sync};
}
