import vert from './shaders/fullscreen.vert.glsl?raw';
import frag from './shaders/breakthrough.frag.glsl?raw';
import type { Params } from './math/parameters';
import { spectralSamples } from './math/parameters';

export class Renderer {
  readonly canvas:HTMLCanvasElement; readonly gl:WebGL2RenderingContext; readonly program:WebGLProgram; readonly uniforms:Record<string,WebGLUniformLocation>; private buffer:WebGLBuffer; private scale=1; private lastResize=0;
  constructor(canvas:HTMLCanvasElement){
    this.canvas=canvas; const gl=canvas.getContext('webgl2',{antialias:false,alpha:false});
    if(!gl) throw new Error('WebGL2 is unavailable. Please use a current browser with WebGL2 enabled; WebGPU is not required.');
    this.gl=gl; this.program=this.makeProgram(vert,frag); this.uniforms={};
    const names=['uResolution','uTime','uProgress','uDuration','uDiamondCompleteTime','uDiamondHoldDuration','uSpectralEmergenceDuration','uSpectralExpansionDuration','uEcstaticHoldDuration','uMorphStart','uMorphEnd','uCouplingStart','uRotationBuildStart','uRotationBuildEnd','uC','uR','uA','uEpsilon','uFilaments','uInitialLines','uPeakLines','uRevealSoftness','uStartSpread','uEndSpread','uOmega0','uOmega1','uSpeedRatio','uCounterRotation','uBaseImperfection','uPeakImperfection','uLargeBulgeStrength','uPinchStrength','uSpacingIrregularity','uBrightnessLandmarkStrength','uInitialHaloWidth','uDifferentialRotation','uTravellingEnergyFrequency','uTravellingEnergySpeed','uRadialBreathing','uPreConvergenceEnergy','uConvergenceImpulse','uSettlingStrength','uFinalResidualMotion','uDepth','uParallax','uCoreWidth','uHaloWidth','uExposure','uBackground','uSeed','uSpectralSamples','uSpectralExpansionSpeed','uSpectralExpansionAcceleration','uPrimaryBandFrequency','uSecondaryBandAmount','uBandSoftness','uBandWidth','uXExpansionScale','uYExpansionScale','uZExpansionScale','uDepthStretch','uVolumetricDensity','uSpectralSaturation','uSpectralExposure','uSpectralEmissionIntensity','uInitialSpectralBrightness','uChromaticAmbientStrength','uBandCentreChromaticHighlight','uInternalRidgeIntensity','uDistantChromaticFill','uDepthAbsorption','uOverlapWhiteningThreshold','uOverlapWhiteningSoftness','uOverlapWhiteningStrength','uVioletLuminanceBoost','uBlueLuminanceBoost','uRedLuminanceBoost','uHighlightColourPreservation','uCentralWhiteStrength','uOverlapWhitening','uWaveDeformation','uEcstaticPulseStrength','uCameraDrift','uResidualDiamondVisibility','uReducedIntensity','uDiamondSpectralFadeDuration','uResidualCentralGlow'];
    for(const name of names)this.uniforms[name]=gl.getUniformLocation(this.program,name)!;
    this.buffer=gl.createBuffer()!; gl.bindBuffer(gl.ARRAY_BUFFER,this.buffer); gl.bufferData(gl.ARRAY_BUFFER,new Float32Array([-1,-1,3,-1,-1,3]),gl.STATIC_DRAW); const loc=gl.getAttribLocation(this.program,'aPosition'); gl.enableVertexAttribArray(loc); gl.vertexAttribPointer(loc,2,gl.FLOAT,false,0,0); this.resize(); addEventListener('resize',()=>this.resize());
  }
  private makeProgram(v:string,f:string){const g=this.gl,compile=(type:number,src:string)=>{const s=g.createShader(type)!;g.shaderSource(s,src);g.compileShader(s);if(!g.getShaderParameter(s,g.COMPILE_STATUS))throw new Error(g.getShaderInfoLog(s)||'Shader compilation failed');return s;};const p=g.createProgram()!;g.attachShader(p,compile(g.VERTEX_SHADER,v));g.attachShader(p,compile(g.FRAGMENT_SHADER,f));g.linkProgram(p);if(!g.getProgramParameter(p,g.LINK_STATUS))throw new Error(g.getProgramInfoLog(p)||'Shader link failed');return p;}
  resize(){const now=performance.now();if(now-this.lastResize<30)return;this.lastResize=now;const d=Math.min(devicePixelRatio||1,1.5)*this.scale;this.canvas.width=Math.max(1,Math.floor(innerWidth*d));this.canvas.height=Math.max(1,Math.floor(innerHeight*d));this.gl.viewport(0,0,this.canvas.width,this.canvas.height);}
  setScale(s:number){this.scale=Math.max(.5,Math.min(1.5,s));this.resize();}
  render(time:number,p:Params){const g=this.gl;g.useProgram(this.program);const u=this.uniforms;const set=(n:string,v:number)=>g.uniform1f(u[n],v);g.uniform2f(u.uResolution,this.canvas.width,this.canvas.height);
    set('uTime',time);set('uProgress',p.progress);set('uDuration',p.duration);set('uDiamondCompleteTime',p.diamondCompleteTime);set('uDiamondHoldDuration',p.diamondHoldDuration);set('uSpectralEmergenceDuration',p.spectralEmergenceDuration);set('uSpectralExpansionDuration',p.spectralExpansionDuration);set('uEcstaticHoldDuration',p.ecstaticHoldDuration);set('uMorphStart',p.morphStart);set('uMorphEnd',p.morphEnd);set('uCouplingStart',p.couplingStart);set('uRotationBuildStart',p.rotationBuildStart);set('uRotationBuildEnd',p.rotationBuildEnd);set('uC',p.c);set('uR',p.r);set('uA',p.a);set('uEpsilon',p.epsilon);set('uFilaments',p.filaments);set('uInitialLines',p.initialLines);set('uPeakLines',p.peakLines);set('uRevealSoftness',p.revealSoftness);set('uStartSpread',p.startSpread);set('uEndSpread',p.endSpread);set('uOmega0',p.omega0);set('uOmega1',p.omega1);set('uSpeedRatio',p.speedRatio);set('uCounterRotation',p.counterRotation?1:0);set('uBaseImperfection',p.baseImperfection);set('uPeakImperfection',p.peakImperfection);set('uLargeBulgeStrength',p.largeBulgeStrength);set('uPinchStrength',p.pinchStrength);set('uSpacingIrregularity',p.spacingIrregularity);set('uBrightnessLandmarkStrength',p.brightnessLandmarkStrength);set('uInitialHaloWidth',p.initialHaloWidth);set('uDifferentialRotation',p.differentialRotation);set('uTravellingEnergyFrequency',p.travellingEnergyFrequency);set('uTravellingEnergySpeed',p.travellingEnergySpeed);set('uRadialBreathing',p.radialBreathing);set('uPreConvergenceEnergy',p.preConvergenceEnergy);set('uConvergenceImpulse',p.convergenceImpulse);set('uSettlingStrength',p.settlingStrength);set('uFinalResidualMotion',p.finalResidualMotion);set('uDepth',p.depth);set('uParallax',p.parallax);set('uCoreWidth',p.coreWidth);set('uHaloWidth',p.haloWidth);set('uExposure',p.exposure);set('uBackground',p.background);set('uSeed',12.7);set('uSpectralSamples',spectralSamples[p.quality]);
    set('uSpectralExpansionSpeed',p.spectralExpansionSpeed);set('uSpectralExpansionAcceleration',p.spectralExpansionAcceleration);set('uPrimaryBandFrequency',p.primaryBandFrequency);set('uSecondaryBandAmount',p.secondaryBandAmount);set('uBandSoftness',p.bandSoftness);set('uBandWidth',p.bandWidth);set('uXExpansionScale',p.xExpansionScale);set('uYExpansionScale',p.yExpansionScale);set('uZExpansionScale',p.zExpansionScale);set('uDepthStretch',p.depthStretch);set('uVolumetricDensity',p.volumetricDensity);set('uSpectralSaturation',p.spectralSaturation);set('uSpectralExposure',p.spectralExposure);set('uSpectralEmissionIntensity',p.spectralEmissionIntensity);set('uInitialSpectralBrightness',p.initialSpectralBrightness);set('uChromaticAmbientStrength',p.chromaticAmbientStrength);set('uBandCentreChromaticHighlight',p.bandCentreChromaticHighlight);set('uInternalRidgeIntensity',p.internalRidgeIntensity);set('uDistantChromaticFill',p.distantChromaticFill);set('uDepthAbsorption',p.depthAbsorption);set('uOverlapWhiteningThreshold',p.overlapWhiteningThreshold);set('uOverlapWhiteningSoftness',p.overlapWhiteningSoftness);set('uOverlapWhiteningStrength',p.overlapWhiteningStrength);set('uVioletLuminanceBoost',p.violetLuminanceBoost);set('uBlueLuminanceBoost',p.blueLuminanceBoost);set('uRedLuminanceBoost',p.redLuminanceBoost);set('uHighlightColourPreservation',p.highlightColourPreservation);set('uCentralWhiteStrength',p.centralWhiteStrength);set('uOverlapWhitening',p.overlapWhitening);set('uWaveDeformation',p.waveDeformation);set('uEcstaticPulseStrength',p.ecstaticPulseStrength);set('uCameraDrift',p.cameraDrift);set('uResidualDiamondVisibility',p.residualDiamondVisibility);set('uReducedIntensity',p.reducedIntensity?1:0);set('uDiamondSpectralFadeDuration',p.diamondSpectralFadeDuration);set('uResidualCentralGlow',p.residualCentralGlow);g.drawArrays(g.TRIANGLES,0,3);
  }
}
