import vert from './shaders/fullscreen.vert.glsl?raw';
import frag from './shaders/breakthrough.frag.glsl?raw';
import strandVert from './shaders/filaments3d.vert.glsl?raw';
import strandFrag from './shaders/filaments3d.frag.glsl?raw';
import type { Params } from './math/parameters';
import { spectralSamples } from './math/parameters';

export class Renderer {
  readonly canvas:HTMLCanvasElement;
  readonly gl:WebGL2RenderingContext;
  readonly program:WebGLProgram;
  readonly uniforms:Record<string,WebGLUniformLocation>={};
  private readonly strandProgram:WebGLProgram;
  private readonly strandUniforms:Record<string,WebGLUniformLocation>={};
  private readonly strandVao:WebGLVertexArrayObject;
  private readonly strandVertexCount:number;
  private readonly buffer:WebGLBuffer;
  private scale=1;
  private lastResize=0;

  constructor(canvas:HTMLCanvasElement){
    this.canvas=canvas;
    const gl=canvas.getContext('webgl2',{antialias:false,alpha:false});
    if(!gl) throw new Error('WebGL2 is unavailable. Please use a current browser with WebGL2 enabled; WebGPU is not required.');
    this.gl=gl;
    this.program=this.makeProgram(vert,frag);
    this.strandProgram=this.makeProgram(strandVert,strandFrag);
    const fullscreenNames=['uResolution','uTime','uProgress','uDuration','uDiamondCompleteTime','uDiamondHoldDuration','uSpectralEmergenceDuration','uSpectralExpansionDuration','uEcstaticHoldDuration','uMorphStart','uMorphEnd','uCouplingStart','uRotationBuildStart','uRotationBuildEnd','uC','uR','uA','uEpsilon','uFilaments','uInitialLines','uPeakLines','uRevealSoftness','uStartSpread','uEndSpread','uOmega0','uOmega1','uSpeedRatio','uCounterRotation','uBaseImperfection','uPeakImperfection','uLargeBulgeStrength','uPinchStrength','uSpacingIrregularity','uBrightnessLandmarkStrength','uInitialHaloWidth','uDifferentialRotation','uTravellingEnergyFrequency','uTravellingEnergySpeed','uRadialBreathing','uPreConvergenceEnergy','uConvergenceImpulse','uSettlingStrength','uFinalResidualMotion','uDepth','uParallax','uCoreWidth','uHaloWidth','uExposure','uBackground','uSeed','uSpectralSamples','uSpectralExpansionSpeed','uSpectralExpansionAcceleration','uPrimaryBandFrequency','uSecondaryBandAmount','uBandSoftness','uBandWidth','uXExpansionScale','uYExpansionScale','uZExpansionScale','uDepthStretch','uVolumetricDensity','uSpectralSaturation','uSpectralVibrance','uSpectralExposure','uSpectralEmissionIntensity','uInitialSpectralBrightness','uChromaticAmbientStrength','uNeutralAmbientStrength','uDepthChromaPreservation','uDominantLayerColourPreservation','uBandCentreChromaticHighlight','uInternalRidgeIntensity','uDistantChromaticFill','uChromaticBloomStrength','uDepthAbsorption','uOverlapWhiteningThreshold','uOverlapWhiteningSoftness','uOverlapWhiteningStrength','uVioletLuminanceBoost','uBlueLuminanceBoost','uRedLuminanceBoost','uHighlightColourPreservation','uCentralWhiteStrength','uOverlapWhitening','uWaveDeformation','uEcstaticPulseStrength','uCameraDrift','uResidualDiamondVisibility','uDepthEffectStrength','uDepthIntroductionPoint','uFilamentBaseDepthSpread','uDepthPathAmplitude','uPlaneTilt','uPlaneTiltVariation','uDepthPerspectiveStrength','uNearWidthScale','uFarWidthScale','uNearBrightnessScale','uFarBrightnessScale','uDepthParallax','uDepthAtmosphericAttenuation','uConvergenceDepthCollapse','uOpeningColourSaturation','uOpeningWarmth','uBroadFieldMotion','uRadialPropagationSpeed','uDirectionalSweepSpeed','uZDepthMotion','uDensityWaveStrength','uDensityWaveSpeed','uSurfaceWarpAmount','uRainbowHoldDuration','uEnableFinalSoftLight','uSoftLightTransitionDuration','uSoftLightHoldDuration','uSoftLightBrightness','uSoftLightWarmth','uSoftLightUniformity','uPearlescentResidualAmount','uFinalBackgroundDarkness','uSoftLightOpacity','uFinalLayerSpread','uFinalSpatialVariation','uDarkGapStrength','uStaticWarpAmount','uFinalEdgeLight','uReducedIntensity','uDiamondSpectralFadeDuration','uResidualCentralGlow','uTrue3DStrands'];
    const strandNames=['uResolution','uProgress','uDuration','uDiamondCompleteTime','uC','uR','uFilaments','uInitialLines','uPeakLines','uRevealSoftness','uOmega0','uOmega1','uSpeedRatio','uCounterRotation','uBaseImperfection','uDifferentialRotation','uBrightnessLandmarkStrength','uDepthIntroductionTime','uMaxPlaneTilt','uPlaneTiltVariation3D','uBaseDepthSpread3D','uOrbitZAmplitude','uSecondaryZAmplitude','uPerspectiveStrength3D','uNearWidthScale3D','uFarWidthScale3D','uNearBrightnessScale3D','uFarBrightnessScale3D','uDepthAttenuation3D','uCoreOpacity3D','uInitialStripWidth3D','uEnergeticStripWidth3D','uInitialGlowScale3D','uEnergeticGlowScale3D','uInitialCoreEmission3D','uPeakCoreEmission3D','uInitialHaloEmission3D','uPeakHaloEmission3D','uBrightnessRiseStartTime3D','uBrightnessRiseDuration3D','uBrightnessExponent3D','uOpeningBronzeColour3D','uEnergeticBronzeGold3D','uEnableDepartures','uDepartureEarliestTime','uDepartureLatestTime','uDepartureDuration','uDepartingStrandProportion','uStrongDepartureProportion','uTangentContinuationStrength','uDepartureLength','uHorizontalBend','uVerticalBend','uZBend','uEndTaper','uSideContainment3D','uDepartureCollapseTiming','uGlow'];
    for(const name of fullscreenNames)this.uniforms[name]=gl.getUniformLocation(this.program,name)!;
    for(const name of strandNames)this.strandUniforms[name]=gl.getUniformLocation(this.strandProgram,name)!;
    for(const name of ['uGoldTransitionStartTime3D','uGoldTransitionDuration3D','uMiddleSoftGold3D','uEnergeticChampagne3D','uPeakSoftGold3D','uGoldSoftness3D','uNearDiamondColourInfluence3D','uNearDepthGoldShift3D','uHaloGoldSoftness3D'])this.strandUniforms[name]=gl.getUniformLocation(this.strandProgram,name)!;
    this.buffer=gl.createBuffer()!; gl.bindBuffer(gl.ARRAY_BUFFER,this.buffer); gl.bufferData(gl.ARRAY_BUFFER,new Float32Array([-1,-1,3,-1,-1,3]),gl.STATIC_DRAW); const loc=gl.getAttribLocation(this.program,'aPosition'); gl.enableVertexAttribArray(loc); gl.vertexAttribPointer(loc,2,gl.FLOAT,false,0,0);
    const segments=96,data=new Float32Array((segments+1)*4); for(let i=0;i<=segments;i++){const k=i*4,t=i/segments*6.2831853;data[k]=t;data[k+1]=-1;data[k+2]=t;data[k+3]=1;}
    this.strandVertexCount=(segments+1)*2; this.strandVao=gl.createVertexArray()!; gl.bindVertexArray(this.strandVao); const strandBuffer=gl.createBuffer()!; gl.bindBuffer(gl.ARRAY_BUFFER,strandBuffer); gl.bufferData(gl.ARRAY_BUFFER,data,gl.STATIC_DRAW); gl.enableVertexAttribArray(0); gl.vertexAttribPointer(0,1,gl.FLOAT,false,8,0); gl.enableVertexAttribArray(1); gl.vertexAttribPointer(1,1,gl.FLOAT,false,8,4); gl.bindVertexArray(null); this.resize(); addEventListener('resize',()=>this.resize());
  }

  private makeProgram(v:string,f:string){const g=this.gl,compile=(type:number,src:string)=>{const s=g.createShader(type)!;g.shaderSource(s,src);g.compileShader(s);if(!g.getShaderParameter(s,g.COMPILE_STATUS))throw new Error(g.getShaderInfoLog(s)||'Shader compilation failed');return s;};const p=g.createProgram()!;g.attachShader(p,compile(g.VERTEX_SHADER,v));g.attachShader(p,compile(g.FRAGMENT_SHADER,f));g.linkProgram(p);if(!g.getProgramParameter(p,g.LINK_STATUS))throw new Error(g.getProgramInfoLog(p)||'Shader link failed');return p;}
  resize(){const now=performance.now();if(now-this.lastResize<30)return;this.lastResize=now;const d=Math.min(devicePixelRatio||1,1.5)*this.scale;this.canvas.width=Math.max(1,Math.floor(innerWidth*d));this.canvas.height=Math.max(1,Math.floor(innerHeight*d));this.gl.viewport(0,0,this.canvas.width,this.canvas.height);}
  setScale(s:number){this.scale=Math.max(.5,Math.min(1.5,s));this.resize();}
  private setValues(target:Record<string,WebGLUniformLocation>,values:Record<string,number>){for(const [name,value] of Object.entries(values))this.gl.uniform1f(target[name],value);}
  private paramsToUniforms(names:string[],p:Params,target:Record<string,WebGLUniformLocation>){const values:Record<string,number>={};for(const name of names){if(name==='uResolution'){this.gl.uniform2f(target[name],this.canvas.width,this.canvas.height);continue;}const key=name.slice(1,2).toLowerCase()+name.slice(2) as keyof Params;const raw=p[key];if(typeof raw==='number')values[name]=raw;else if(typeof raw==='boolean')values[name]=raw?1:0;}return values;}
  private draw3D(p:Params){const g=this.gl;if(!p.enableTrue3DStrands||p.progress*p.duration>p.diamondCompleteTime)return;g.clear(g.DEPTH_BUFFER_BIT);g.useProgram(this.strandProgram);const values=this.paramsToUniforms(Object.keys(this.strandUniforms),p,this.strandUniforms);values.uGlow=0;this.setValues(this.strandUniforms,values);g.bindVertexArray(this.strandVao);g.enable(g.DEPTH_TEST);g.depthFunc(g.LEQUAL);g.enable(g.BLEND);g.depthMask(true);g.blendFunc(g.SRC_ALPHA,g.ONE_MINUS_SRC_ALPHA);g.drawArraysInstanced(g.TRIANGLE_STRIP,0,this.strandVertexCount,Math.min(96,Math.floor(p.filaments)));g.depthMask(false);g.blendFunc(g.SRC_ALPHA,g.ONE);g.uniform1f(this.strandUniforms.uGlow,1);g.drawArraysInstanced(g.TRIANGLE_STRIP,0,this.strandVertexCount,Math.min(96,Math.floor(p.filaments)));g.depthMask(true);g.disable(g.BLEND);g.disable(g.DEPTH_TEST);g.bindVertexArray(null);}
  render(time:number,p:Params){const g=this.gl;g.disable(g.DEPTH_TEST);g.disable(g.BLEND);g.useProgram(this.program);const values=this.paramsToUniforms(Object.keys(this.uniforms),p,this.uniforms);values.uTime=time;values.uSeed=12.7;values.uSpectralSamples=spectralSamples[p.quality];values.uTrue3DStrands=p.enableTrue3DStrands?1:0;this.setValues(this.uniforms,values);g.drawArrays(g.TRIANGLES,0,3);this.draw3D(p);}
}
